### PR TITLE
add rust

### PR DESCRIPTION
**Pull request by yaghmaie**
Hello,

Thank you very much for sharing this on YouTube. I really enjoyed both doing the exercise and writing weird hard to read rust code.

Please let me know if anything has to be fixed or could be improved.

Thanks

### CODE REVIEW

**Comment by codecop** [comment]
Thank you this is welcomed. I have some questions.
1. should the lock file be committed? In practice environments usually everybody has his/her own versions etc.
2. can the main file be called yatzi instead of category?
3. You use a lot of map/filter/iter constructs. This is already an improvement of the code. Is it possible to do plain loops with imperative code instead like most other code like the C or Java one?

**Comment by yaghmaie** [comment]
Thanks for the review.
1. That's correct the package has no dependencies to be locked anyway.
2. Actually the main file would be `lib.rs` which includes `category` so the imports would look something like `use yatzy::category::ones` that reads nicely. But it is possible to have both.
3. That's fair. I don't want to only have bad imperative code, but I'll make them worse.

**Comment by codecop** [comment]
Thank you. Sorry that I am picky here: Usually the code of ports is as similar as possible, so all participants have the same experience regardless of which language they use and/or to support a workshop/coding dojo in a group which uses different languages at the same time. For example your chance is

```
    let mut t = 0;
    t = t+ r[0];
    t= t + r[1]; 
    t +=r[2]+r[3];

    return t + r[4]
```
but the Java or JavaScript is

```
   var total = 0;
    total += d1;
    total += d2;
    total += d3;
    total += d4;
    total += d5;
    return total;
```    
While these are equivalent, the second one uses named parameters instead of an array and increments total once in each line. Also the total is `total` and not `t`. While some things are not possible in some languages, could you follow the code as much as possible in names, structures and so on. E.g. there is no use of iter/foreach/map in the original code, that was the reason I mentioned it in the previous comment. I was not clear. It is not as much as to make the code worse, but to make it consistent with other languages.

When I do this I compare the source of my port - usually my strongest language - and compare it line by line with my port. This helps me flush out the last inconsistencies. Even comments and (rarely) bad formatting could be ported and preserved. Please have a try

**Comment by yaghmaie** [comment]
I just didn't know they had to be similar. I'll fix it.

**Comment by yaghmaie** [comment]
I copied the Java code and tried to make as little changes as possible only to get it compile on rust

**Comment by codecop** [comment]
Thank you, excellent work. Sorry for the confusion and thank you for your patience. This can be merged,
@emilybache please merge.

**Comment by emilybache** [comment]
Thankyou both for your work on this. I appreciate it.

**Comment by yaghmaie** [comment]
I'm learning a lot so I'd be glad if I could give something back 🙏🏻🙏🏻

**Pull request merged**
